### ISSUE TITLE
license mit/bsd

### ISSUE THREAD

**Issue by glycerine** [kanocz/lcvpn#5]
The lcvpn project looks quite interesting, thank you. I would like experiment with it.

Would you consider changing the license to MIT or BSD (like Go)?

**Comment by kanocz** [comment]
Theoretically it's not a problem to change to Apache license (it can't be MIT due to netlink part). On the other hand I see no reason for this - it's not a library but application, so if you'll use it on your servers on in your organisation you can do this without any restrictions - you are the user and you need to publish changes only to yourself.

**Comment by glycerine** [comment]
Good point. It's just that I prefer to embed all components as libraries.

Apache license would be welcome.

**Comment by kanocz** [comment]
How will you include application as library? :)
P.S.: I need some time to read about Apache license and only than can do this change

**Comment by glycerine** [comment]
> How will you include application as library? :)

:) The basics of converting to a library would be renaming main() to StartLcvpn() and then calling `go StartLcvpn()` from the the embedding application's main().

**Comment by glycerine** [comment]
Excellent. Thank you, Anton.
